package ai.konduit.pipelinegenerator.main.install;

import ai.konduit.pipelinegenerator.main.Info;
import org.zeroturnaround.exec.ProcessExecutor;
import picocli.CommandLine;

import java.io.File;
import java.util.Arrays;
import java.util.concurrent.Callable;
@CommandLine.Command(name = "sdk-install",mixinStandardHelpOptions = false,description = "Installs a python wheel generated from the generate-sdk command to the local python managed by kompile.")
public class InstallSDK implements Callable<Integer> {
    @CommandLine.Option(names = {"--pathToWheel"},description = "Path to a python wheel generated by the generate-image-and-sdk command.",required = true)
    private File pathToWheel;

    public InstallSDK() {
    }

    @Override
    public Integer call() throws Exception {
        File pythonDir = Info.pythonDirectory();
        File pipExec = new File(pythonDir,"bin/pip");
        int   exitValue =  new ProcessExecutor().environment(System.getenv())
                .command(Arrays.asList(pipExec.getAbsolutePath() ,"install" ,pathToWheel.getAbsolutePath()))
                .readOutput(true)
                .redirectOutput(System.out)
                .start().getFuture().get().getExitValue();
        return exitValue;
    }
}
