'\" t
.\"     Title: exec-step-create-nd4jtensorflow
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-07-09
.\"    Manual: Exec Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "EXEC\-STEP\-CREATE\-ND4JTENSORFLOW" "1" "2022-07-09" "" "Exec Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
.sp
exec\-step\-create\-ND4JTENSORFLOW \-
.SH "SYNOPSIS"
.sp
\fBexec step\-create ND4JTENSORFLOW\fP \fB\-\-fileFormat\fP=\fIPARAM\fP [\fB\-\-modelUri\fP=\fIPARAM\fP]
[\fB\-\-inputNames\fP=\fIPARAM\fP]... [\fB\-\-outputNames\fP=\fIPARAM\fP]...
.SH "DESCRIPTION"

.SH "OPTIONS"
.sp
\fB\-\-fileFormat\fP=\fIPARAM\fP
.RS 4
The file format (either json or yaml/yml) to output the pipeline step in
.RE
.sp
\fB\-\-inputNames\fP=\fIPARAM\fP
.RS 4
A list of names of the input placeholders.
.RE
.sp
\fB\-\-modelUri\fP=\fIPARAM\fP
.RS 4
Uniform Resource Identifier of model
.RE
.sp
\fB\-\-outputNames\fP=\fIPARAM\fP
.RS 4
A list of names of the output arrays \- i.e., what should be predicted.
.RE