'\" t
.\"     Title: info
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-07-09
.\"    Manual: Info Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "INFO" "1" "2022-07-09" "" "Info Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
info \- Display information on current kompile installation.
.SH "SYNOPSIS"
.sp
\fBinfo\fP
.SH "DESCRIPTION"
.sp
Display information on current kompile installation.