'\" t
.\"     Title: kompile
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-07-09
.\"    Manual: Kompile Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "KOMPILE" "1" "2022-07-09" "" "Kompile Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
.sp
kompile \-
.SH "SYNOPSIS"
.sp
\fBkompile\fP [COMMAND]
.SH "DESCRIPTION"

.SH "COMMANDS"
.sp
\fBexec\fP
.RS 4
Execution configuration related classes for running ML pipelines
.RE
.sp
\fBbuild\fP
.RS 4
Configuration namespace for commands related to building native image binaries and SDKs
.RE
.sp
\fBconfig\fP
.RS 4
Generate configuration
.RE
.sp
\fBhelper\fP
.RS 4
Entry point for higher level helpers containing common patterns for pipeline creation
.RE
.sp
\fBinfo\fP
.RS 4
Display information on current kompile installation.
.RE
.sp
\fBinstall\fP, \fBuninstall\fP, \fBbootstrap\fP
.RS 4
Sets up SDK for building images.
.RE
.sp
\fBmodel\fP
.RS 4
Utilities related to models including execution and debugging.
.RE