'\" t
.\"     Title: kompile-exec-step-create-draw_points
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-07-09
.\"    Manual: Kompile Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "KOMPILE\-EXEC\-STEP\-CREATE\-DRAW_POINTS" "1" "2022-07-09" "" "Kompile Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
.sp
kompile\-exec\-step\-create\-DRAW_POINTS \-
.SH "SYNOPSIS"
.sp
\fBkompile exec step\-create DRAW_POINTS\fP [\fB\-\-DEFAULT_NO_POINT_COLOR\fP=\fIPARAM\fP]
[\fB\-\-DEFAULT_OUTPUT_NAME\fP=\fIPARAM\fP]
\fB\-\-fileFormat\fP=\fIPARAM\fP [\fB\-\-height\fP=\fIPARAM\fP]
[\fB\-\-image\fP=\fIPARAM\fP]
[\fB\-\-imageToNDArrayConfig\fP=\fIPARAM\fP]
[\fB\-\-noClassColor\fP=\fIPARAM\fP]
[\fB\-\-outputName\fP=\fIPARAM\fP] [\fB\-\-radius\fP=\fIPARAM\fP]
[\fB\-\-width\fP=\fIPARAM\fP] [\fB\-\-classColors\fP=\fIPARAM\fP]...
[\fB\-\-points\fP=\fIPARAM\fP]...
.SH "DESCRIPTION"

.SH "OPTIONS"
.sp
\fB\-\-classColors\fP=\fIPARAM\fP
.RS 4
This is an optional field which specifies the mapping of colors to use for each class. The color can be a hex/HTML string like"#788E87", an RGB value like RGB \- "rgb(128,0,255)" or  it can be from a set of predefined HTML color names: [white, silver, gray, black, red, maroon, yellow, olive, lime, green, aqua, teal, blue, navy, fuchsia, purple]
.RE
.sp
\fB\-\-DEFAULT_NO_POINT_COLOR\fP=\fIPARAM\fP, \fB\-\-DEFAULT_OUTPUT_NAME\fP=\fIPARAM\fP, \fB\-\-fileFormat\fP=\fIPARAM\fP
.RS 4
The file format (either json or yaml/yml) to output the pipeline step in
.RE
.sp
\fB\-\-height\fP=\fIPARAM\fP
.RS 4
Must be provided when "image" isn\(cqt set. Used to resolve position of points with relative addressing (dimensions between 0 and 1)
.RE
.sp
\fB\-\-image\fP=\fIPARAM\fP
.RS 4
An optional field, specifying the name of the image to be drawn on
.RE
.sp
\fB\-\-imageToNDArrayConfig\fP=\fIPARAM\fP
.RS 4
Used to account for the fact that n\-dimensional array from ImageToNDArrayConfig may be used to crop images before passing to the network, when the image aspect ratio doesn\(cqt match the NDArray aspect ratio. This allows the step to determine the subset of the image actually passed to the network.
.RE
.sp
\fB\-\-noClassColor\fP=\fIPARAM\fP
.RS 4
Color belongs to non\-label data
.RE
.sp
\fB\-\-outputName\fP=\fIPARAM\fP
.RS 4
Name of the output image
.RE
.sp
\fB\-\-points\fP=\fIPARAM\fP
.RS 4
Name of the input data fields containing the points to be drawn. Accepts both single points and lists of points. Accepts both relative and absolute addressed points.
.RE
.sp
\fB\-\-radius\fP=\fIPARAM\fP
.RS 4
Optional. Point radius on drawn image. Default = 5px
.RE
.sp
\fB\-\-width\fP=\fIPARAM\fP
.RS 4
Must be provided when "image" isn\(cqt set. Used to resolve position of points with relative addressing (dimensions between 0 and 1)
.RE