'\" t
.\"     Title: kompile-exec-pipeline-generate
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-07-09
.\"    Manual: Kompile Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "KOMPILE\-EXEC\-PIPELINE\-GENERATE" "1" "2022-07-09" "" "Kompile Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
.sp
kompile\-exec\-pipeline\-generate \-
.SH "SYNOPSIS"
.sp
\fBkompile exec pipeline\-generate\fP \fB\-\-output\-file\fP=\fI<outputFile>\fP
[\fB\-\-output\-format\fP=\fI<format>\fP] \fB\-\-pipeline\fP=\fI<pipeline>\fP
.SH "DESCRIPTION"

.SH "OPTIONS"
.sp
\fB\-\-output\-file\fP=\fI<outputFile>\fP
.RS 4
Output file
.RE
.sp
\fB\-\-output\-format\fP=\fI<format>\fP
.RS 4
Output format (json or yml)
.RE
.sp
\fB\-\-pipeline\fP=\fI<pipeline>\fP
.RS 4
Pipeline String
.RE