'\" t
.\"     Title: kompile-model-convert
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-07-09
.\"    Manual: Kompile Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "KOMPILE\-MODEL\-CONVERT" "1" "2022-07-09" "" "Kompile Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
kompile\-model\-convert \- Convert models from tensorflow or onnx to samediff and keras h5 to dl4j zip.
.SH "SYNOPSIS"
.sp
\fBkompile model convert\fP \fB\-\-format\fP=\fI<format>\fP \fB\-\-inputFile\fP=\fI<inputFile>\fP
[\fB\-\-kerasNetworkType\fP=\fI<kerasNetworkType>\fP]
[\fB\-\-outputFile\fP=\fI<outputFile>\fP]
.SH "DESCRIPTION"
.sp
Convert models from tensorflow or onnx to samediff and keras h5 to dl4j zip.
.SH "OPTIONS"
.sp
\fB\-\-format\fP=\fI<format>\fP
.RS 4
Specify: tensorflow, keras or onnx to convert to samediff format. Optional if the specified inputFile is in the correct format (.h5/.hdf5 (keras) .pb (tensorflow) or .onnx (onnx))
.RE
.sp
\fB\-\-inputFile\fP=\fI<inputFile>\fP
.RS 4
Input file for conversion
.RE
.sp
\fB\-\-kerasNetworkType\fP=\fI<kerasNetworkType>\fP
.RS 4
Specify: sequential or functional
.RE
.sp
\fB\-\-outputFile\fP=\fI<outputFile>\fP
.RS 4
File output path: optional default will be the original file name minus the format followed by .fb for flatbuffers the samediff format or .zip the dl4j format when converting from keras.
.RE