'\" t
.\"     Title: kompile-bootstrap
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-07-09
.\"    Manual: Kompile Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "KOMPILE\-BOOTSTRAP" "1" "2022-07-09" "" "Kompile Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
kompile\-bootstrap \- Sets up SDK for building images.
.SH "SYNOPSIS"
.sp
\fBkompile bootstrap\fP [\fB\-\-createFolder\fP] [\fB\-\-forceBootstrap\fP]
.SH "DESCRIPTION"
.sp
Sets up SDK for building images.
.SH "OPTIONS"
.sp
\fB\-\-createFolder\fP
.RS 4
Whether to create home folder or not, defaults to true
.RE
.sp
\fB\-\-forceBootstrap\fP
.RS 4
Whether to force creation of directory or not.
.RE