'\" t
.\"     Title: sequence-pipeline-creator
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-07-09
.\"    Manual: Sequence-pipeline-creator Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "SEQUENCE\-PIPELINE\-CREATOR" "1" "2022-07-09" "" "Sequence\-pipeline\-creator Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
.sp
sequence\-pipeline\-creator \-
.SH "SYNOPSIS"
.sp
\fBsequence\-pipeline\-creator\fP [\fB\-\-file\-format\fP=\fI<format>\fP] \fB\-\-pipeline\fP=\fI<pipelineStep>\fP
[\fB\-\-pipeline\fP=\fI<pipelineStep>\fP]...
.SH "DESCRIPTION"

.SH "OPTIONS"
.sp
\fB\-\-file\-format\fP=\fI<format>\fP
.RS 4
Pipeline String
.RE
.sp
\fB\-\-pipeline\fP=\fI<pipelineStep>\fP
.RS 4
Pipeline String
.RE